
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python-backend
        image: 353203138981.dkr.ecr.us-east-1.amazonaws.com/python-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-backend-svc
spec:
  selector:
    app: python-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
