apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: 353203138981.dkr.ecr.us-east-1.amazonaws.com/react-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-svc
spec:
  selector:
    app: react-frontend
  # This creates an external AWS Load Balancer to expose the service.
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
