apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-processor
  template:
    metadata:
      labels:
        app: go-processor
    spec:
      containers:
      - name: go-processor
        image: 353203138981.dkr.ecr.us-east-1.amazonaws.com/go-processor:latest
        ports:
        - containerPort: 8081